<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class VenueSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $userid = \DB::table('users')->where('name', 'Rob Baartwijk')->value('id');

        $venues = [
            [
                'user_id' => $userid,
                'name' => 'Blues/Rock Café Under The Bridge Alphen aan den Rijn',
                'address' => 'Hooftstraat 165',
                'zip' => '2406 GH',
                'city' => 'Alphen aan den Rijn',
                'state' => 'Zuid-Holland',
                'country' => 'Nederland',
                'phone' => '',
                'email' => '',
                'website' => 'https://underthebridge.nl',
                'description' => 'Het Blues Rock cafe van Alphen aan den Rijn',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userid,
                'name' => 'Theater Castellum Alphen aan den Rijn',
                'address' => 'Rijnplein 1-3',
                'zip' => '2405 DB',
                'city' => 'Alphen aan den Rijn',
                'state' => 'Zuid-Holland',
                'country' => 'Nederland',
                'phone' => '',
                'email' => '',
                'website' => 'https://www.theatercastellum.nl/',
                'description' => 'Theater Castellum Alphen aan den Rijn.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userid,
                'name' => 'Max Alphen aan den Rijn',
                'address' => 'Olympiaweg 2-A',
                'zip' => '2406 LG',
                'city' => 'Alphen aan den Rijn',
                'state' => 'Zuid-Holland',
                'country' => 'Nederland',
                'phone' => '',
                'email' => '',
                'website' => 'https://www.max-alphen.nl/',
                'description' => 'Max Alphen aan den Rijn.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userid,
                'name' => 'Parkvilla Alphen aan den Rijn',
                'address' => 'Cornelis Geellaan 2',
                'zip' => '2406 JG',
                'city' => 'Alphen aan den Rijn',
                'state' => 'Zuid-Holland',
                'country' => 'Nederland',
                'phone' => '',
                'email' => '',
                'website' => 'https://www.parkvilla.nl/',
                'description' => 'Parkvilla Alphen aan den Rijn.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userid,
                'name' => 'Theater Het Kruispunt Barendrecht',
                'address' => 'Middenbaan 111',
                'zip' => '2991 CS',
                'city' => 'Barendrecht',
                'state' => 'Zuid-Holland',
                'country' => 'Nederland',
                'phone' => '',
                'email' => '',
                'website' => 'https://theaterhetkruispunt.nl/',
                'description' => 'Theater Het Kruispunt Barendrecht.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userid,
                'name' => 'Theater De Stoep Spijkenisse',
                'address' => 'Theaterplein 1',
                'zip' => '3201 DH',
                'city' => 'Spijkenisse',
                'state' => 'Zuid-Holland',
                'country' => 'Nederland',
                'phone' => '',
                'email' => '',
                'website' => 'https://theaterdestoep.nl/',
                'description' => 'Theater De Stoep Spijkenisse.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userid,
                'name' => 'Theater De Willem Papendrecht',
                'address' => 'Van der Palmstraat 4',
                'zip' => '3351 HA',
                'city' => 'Papendrecht',
                'state' => 'Zuid-Holland',
                'country' => 'Nederland',
                'phone' => '',
                'email' => '',
                'website' => 'https://theaterdewillem.nl/',
                'description' => 'Theater De Willem Papendrecht.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userid,
                'name' => 'Theater De Mythe Goes',
                'address' => 'Bleekveld 1',
                'zip' => '4461 DD',
                'city' => 'Goes',
                'state' => 'Zeeland',
                'country' => 'Nederland',
                'phone' => '',
                'email' => '',
                'website' => 'https://www.theaterdemythe.nl/',
                'description' => 'Theater De Mythe Goes.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userid,
                'name' => 'Theater De Maagd Bergen op Zoom',
                'address' => 'Grote Markt 32',
                'zip' => '4611 NT',
                'city' => 'Bergen op Zoom',
                'state' => 'Noord-Brabant',
                'country' => 'Nederland',
                'phone' => '',
                'email' => '',
                'website' => 'https://www.demaagd.nl/',
                'description' => 'Theater De Maagd Bergen op Zoom.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userid,
                'name' => 'Theater De Leest Waalwijk',
                'address' => 'Vredesplein 12',
                'zip' => '5142 RA',
                'city' => 'Waalwijk',
                'state' => 'Noord-Brabant',
                'country' => 'Nederland',
                'phone' => '',
                'email' => '',
                'website' => 'https://www.deleest.nl/',
                'description' => 'Theater De Leest Waalwijk.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userid,
                'name' => 'Theater De Lievekamp Oss',
                'address' => 'Raadhuislaan 14',
                'zip' => '5341 GM',
                'city' => 'Oss',
                'state' => 'Noord-Brabant',
                'country' => 'Nederland',
                'phone' => '',
                'email' => '',
                'website' => 'https://www.lievekamp.nl/',
                'description' => 'Theater De Lievekamp Oss.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userid,
                'name' => 'Theater De Bussel Oosterhout',
                'address' => 'Torenstraat 10',
                'zip' => '4901 EJ',
                'city' => 'Oosterhout',
                'state' => 'Noord-Brabant',
                'country' => 'Nederland',
                'phone' => '',
                'email' => '',
                'website' => 'https://www.theaterdebussel.nl/',
                'description' => 'Theater De Bussel Oosterhout.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userid,
                'name' => 'Theater De Voorveghter Hardenberg',
                'address' => 'Badhuisplein 3',
                'zip' => '7772 XA',
                'city' => 'Hardenberg',
                'state' => 'Overijssel',
                'country' => 'Nederland',
                'phone' => '',
                'email' => '',
                'website' => 'https://www.voorveghter.nl/',
                'description' => 'Theater De Voorveghter Hardenberg.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userid,
                'name' => 'Theater De Spiegel Zwolle',
                'address' => 'Spinhuisplein 14',
                'zip' => '8011 ZZ',
                'city' => 'Zwolle',
                'state' => 'Overijssel',
                'country' => 'Nederland',
                'phone' => '',
                'email' => '',
                'website' => 'https://zwolsetheaters.nl/',
                'description' => 'Theater De Spiegel Zwolle.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userid,
                'name' => 'Theater De Meenthe Steenwijk',
                'address' => 'Stationsplein 1',
                'zip' => '8331 GM',
                'city' => 'Steenwijk',
                'state' => 'Overijssel',
                'country' => 'Nederland',
                'phone' => '',
                'email' => '',
                'website' => 'https://www.demeenthe.nl/',
                'description' => 'Theater De Meenthe Steenwijk.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userid,
                'name' => 'Theater De Vest Alkmaar',
                'address' => 'Canadaplein 2',
                'zip' => '1811 KE',
                'city' => 'Alkmaar',
                'state' => 'Noord-Holland',
                'country' => 'Nederland',
                'phone' => '',
                'email' => '',
                'website' => 'https://www.taqatheaterdevest.nl/',
                'description' => 'Theater De Vest Alkmaar.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userid,
                'name' => 'Theater De Kom Nieuwegein',
                'address' => 'Stadsplein 1',
                'zip' => '3431 LZ',
                'city' => 'Nieuwegein',
                'state' => 'Utrecht',
                'country' => 'Nederland',
                'phone' => '',
                'email' => '',
                'website' => 'https://www.dekom.nl/',
                'description' => 'Theater De Kom Nieuwegein.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userid,
                'name' => 'Theater De Flint Amersfoort',
                'address' => 'Coninckstraat 60',
                'zip' => '3811 WK',
                'city' => 'Amersfoort',
                'state' => 'Utrecht',
                'country' => 'Nederland',
                'phone' => '',
                'email' => '',
                'website' => 'https://www.deflint.nl/',
                'description' => 'Theater De Flint Amersfoort.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userid,
                'name' => 'Theater De Lampegiet Veenendaal',
                'address' => 'Kees Stipplein 72',
                'zip' => '3901 TP',
                'city' => 'Veenendaal',
                'state' => 'Utrecht',
                'country' => 'Nederland',
                'phone' => '',
                'email' => '',
                'website' => 'https://www.lampegiet.nl/',
                'description' => 'Theater De Lampegiet Veenendaal.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userid,
                'name' => 'Theater De Tamboer Hoogeveen',
                'address' => 'Hoofdstraat 17',
                'zip' => '7902 EA',
                'city' => 'Hoogeveen',
                'state' => 'Drenthe',
                'country' => 'Nederland',
                'phone' => '',
                'email' => '',
                'website' => 'https://www.detamboer.nl/',
                'description' => 'Theater De Tamboer Hoogeveen.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userid,
                'name' => 'Theater De Nieuwe Kolk Assen',
                'address' => 'Weiersstraat 1',
                'zip' => '9401 ET',
                'city' => 'Assen',
                'state' => 'Drenthe',
                'country' => 'Nederland',
                'phone' => '',
                'email' => '',
                'website' => 'https://www.dnk.nl/',
                'description' => 'The Nieuwe Kolk Assen.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userid,
                'name' => 'Theater De Maaspoort Venlo',
                'address' => 'Oude Markt 30',
                'zip' => '5911 HH',
                'city' => 'Venlo',
                'state' => 'Limburg',
                'country' => 'Nederland',
                'phone' => '',
                'email' => '',
                'website' => 'https://www.maaspoort.nl/',
                'description' => 'Theater De Maaspoort Venlo.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userid,
                'name' => 'Theater Heerlen',
                'address' => 'Burgemeester van Grunsvenplein 145',
                'zip' => '6411 AS',
                'city' => 'Heerlen',
                'state' => 'Limburg',
                'country' => 'Nederland',
                'phone' => '',
                'email' => '',
                'website' => 'https://www.plt.nl/',
                'description' => 'Theater Heerlen.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userid,
                'name' => 'Theater Orpheus Apeldoorn',
                'address' => 'Churchillplein 1',
                'zip' => '7314 BZ',
                'city' => 'Apeldoorn',
                'state' => 'Gelderland',
                'country' => 'Nederland',
                'phone' => '',
                'email' => '',
                'website' => 'https://www.orpheus.nl/',
                'description' => 'Theater Orpheus Apeldoorn.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userid,
                'name' => 'Theater Junushoff Wageningen',
                'address' => 'Plantsoen 3',
                'zip' => '6701 AS',
                'city' => 'Wageningen',
                'state' => 'Gelderland',
                'country' => 'Nederland',
                'phone' => '',
                'email' => '',
                'website' => 'https://www.junushoff.nl/',
                'description' => 'Theater Junushoff Wageningen.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userid,
                'name' => 'Theater aan het Vrijthof Maastricht',
                'address' => 'Vrijthof 47',
                'zip' => '6211 LE',
                'city' => 'Maastricht',
                'state' => 'Limburg',
                'country' => 'Nederland',
                'phone' => '',
                'email' => '',
                'website' => 'https://www.theateraanhetvrijthof.nl/',
                'description' => 'Theater aan het Vrijthof Maastricht.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userid,
                'name' => 'Theater aan de Schie Schiedam',
                'address' => 'Stadserf 1',
                'zip' => '3112 DZ',
                'city' => 'Schiedam',
                'state' => 'Zuid-Holland',
                'country' => 'Nederland',
                'phone' => '',
                'email' => '',
                'website' => 'https://www.theateraandeschie.nl/',
                'description' => 'Theater aan de Schie Schiedam.',
                'created_at' => now(),
                'updated_at' => now(),
            ],


            
            [
                'user_id' => $userid,
                'name' => 'Concertgebouw Amsterdam',
                'address' => 'Concertgebouwplein 10',
                'zip' => '1071 LN',
                'city' => 'Amsterdam',
                'state' => 'Noord-Holland',
                'country' => 'Nederland',
                'phone' => '',
                'email' => '',
                'website' => 'https://www.concertgebouw.nl/',
                'description' => 'Concertgebouw Amsterdam.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userid,
                'name' => 'Paradiso Amsterdam',
                'address' => 'Weteringschans 6-8',
                'zip' => '1017 SG',
                'city' => 'Amsterdam',
                'state' => 'Noord-Holland',
                'country' => 'Nederland',
                'phone' => '',
                'email' => '',
                'website' => 'https://www.paradiso.nl/',
                'description' => 'Paradiso Amsterdam.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userid,
                'name' => 'TivoliVredenburg Utrecht',
                'address' => 'Vredenburgkade 11',
                'zip' => '3511 WC',
                'city' => 'Utrecht',
                'state' => 'Utrecht',
                'country' => 'Nederland',
                'phone' => '',
                'email' => '',
                'website' => 'https://www.tivolivredenburg.nl/',
                'description' => 'TivoliVredenburg Utrecht.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userid,
                'name' => 'AFAS Live Amsterdam',
                'address' => 'ArenA Boulevard 590',
                'zip' => '1101 DS',
                'city' => 'Amsterdam',
                'state' => 'Noord-Holland',
                'country' => 'Nederland',
                'phone' => '',
                'email' => '',
                'website' => 'https://www.afaslive.nl/',
                'description' => 'AFAS Live Amsterdam.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userid,
                'name' => 'Ziggo Dome Amsterdam',
                'address' => 'De Passage 100',
                'zip' => '1101 AX',
                'city' => 'Amsterdam',
                'state' => 'Noord-Holland',
                'country' => 'Nederland',
                'phone' => '',
                'email' => '',
                'website' => 'https://www.ziggodome.nl/',
                'description' => 'Ziggo Dome Amsterdam.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userid,
                'name' => 'Melkweg Amsterdam',
                'address' => 'Lijnbaansgracht 234A',
                'zip' => '1017 PH',
                'city' => 'Amsterdam',
                'state' => 'Noord-Holland',
                'country' => 'Nederland',
                'phone' => '',
                'email' => '',
                'website' => 'https://www.melkweg.nl/',
                'description' => 'Melkweg Amsterdam.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userid,
                'name' => 'Paard Den Haag',
                'address' => 'Prinsegracht 12',
                'zip' => '2512 GA',
                'city' => 'Den Haag',
                'state' => 'Zuid-Holland',
                'country' => 'Nederland',
                'phone' => '',
                'email' => '',
                'website' => 'https://www.paard.nl/',
                'description' => 'Paard Den Haag.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userid,
                'name' => '013 Tilburg',
                'address' => 'Veemarktstraat 44',
                'zip' => '5038 CV',
                'city' => 'Tilburg',
                'state' => 'Noord-Brabant',
                'country' => 'Nederland',
                'phone' => '',
                'email' => '',
                'website' => 'https://www.013.nl/',
                'description' => '013 Tilburg.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userid,
                'name' => 'Doornroosje Nijmegen',
                'address' => 'Stationsplein 11',
                'zip' => '6512 AB',
                'city' => 'Nijmegen',
                'state' => 'Gelderland',
                'country' => 'Nederland',
                'phone' => '',
                'email' => '',
                'website' => 'https://www.doornroosje.nl/',
                'description' => 'Doornroosje Nijmegen.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userid,
                'name' => 'Hedon Zwolle',
                'address' => 'Burgemeester Drijbersingel 7',
                'zip' => '8021 DA',
                'city' => 'Zwolle',
                'state' => 'Overijssel',
                'country' => 'Nederland',
                'phone' => '',
                'email' => '',
                'website' => 'https://www.hedon-zwolle.nl/',
                'description' => 'Hedon Zwolle.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userid,
                'name' => 'Effenaar Eindhoven',
                'address' => 'Dommelstraat 2',
                'zip' => '5611 CK',
                'city' => 'Eindhoven',
                'state' => 'Noord-Brabant',
                'country' => 'Nederland',
                'phone' => '',
                'email' => '',
                'website' => 'https://www.effenaar.nl/',
                'description' => 'Effenaar Eindhoven.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        \DB::table('venues')->insert($venues);

        // \App\Models\Venue::factory(100)->create([]);

    }
}
